### PR TITLE
Delete .DS_Store

### PR DESCRIPTION
**Pull request by liamcannon**
.DS_Store is just a macOS file

### CODE REVIEW

**Review by FuzzyNovaGoblin — CHANGES_REQUESTED** [review]
do it better

**Comment by chrisbendel** [comment]
lmao

**Comment by FuzzyNovaGoblin** [comment]
I mean... it should be in the `.gitignore`

**Comment by liamcannon** [comment]
@FuzzyNovaGoblin fixed

**Review by FuzzyNovaGoblin — APPROVED** [review]
this is better

**Pull request merged**
