### PR TITLE
Editor level saving

### LINKED ISSUE #6: Need standard level save format
Format should be fairly compact, potentially needs support for images

### PR DESCRIPTION
**Pull request by boxbeam**
Ctrl + S can now be used to save the level to a file with a Lua table in it

solves
closes
fixes
resolved
closing keywords 2wg;kn

### CODE REVIEW

**Review by liamcannon — CHANGES_REQUESTED** [review]
Remove level.lua

**Comment by boxbeam** [comment]
> Remove level.lua

i alerhudy did dumb;as

**Comment by boxbeam** [comment]
oops did not mean to close

**Comment by liamcannon** [comment]
Rude

**Review by liamcannon — APPROVED** [review]
Looks good

**Review by GigaRyno — APPROVED** [review]

**Review by FuzzyNovaGoblin — APPROVED** [review]

**Pull request merged**
